GET http://localhost:3000

####
POST http://localhost:3000/login
Content-Type: application/json 
//header : what is the content type

{
    "username": "syazwinapauzi",
    "password": "123456"
}



####
POST http://localhost:3000/register
Content-Type: application/json


{
    "Visitor_id": "0002",
    "Name": "Syazwani Nizam"

}